# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define the proxy function route
[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
